name: Go Test
on: [push]
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - uses: actions/checkout@v3
    - run: go test -v -race ./...
